# Generated by Django 4.2 on 2023-05-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_user_is_aagent_user_is_organiser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='organisation',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='worker.userporfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.agent'),
        ),
    ]
