# Generated by Django 4.2.1 on 2023-06-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_worker_organisation_alter_worker_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.userporfile'),
        ),
    ]
