# Generated by Django 4.2.1 on 2023-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_worker_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phonned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
