# Generated by Django 4.2.1 on 2023-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_alter_worker_phonned'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
